### ISSUE TITLE
Search paging offset should never be grater than number of results

### ISSUE THREAD

**Issue by sweco-semhul** [libris/lxlviewer#19]
Example:
1. Make a full search https://libris-dev.kb.se/find?q=*
2. Go to page 2
3. Select a filter 

stats view @id should not contain offset?
<img width="669" alt="screen shot 2016-06-30 at 14 33 23" src="https://cloud.githubusercontent.com/assets/2656349/16488194/aff92bf8-3ecf-11e6-8978-c5931ba00f17.png">

**Comment by oBlissing** [comment]
Is this handled in client? ping @niklasl

**Comment by niklasl** [comment]
This is an lxltools issue; I'll fix.
