### ISSUE TITLE
Need better pagination in search when getting many results

### ISSUE THREAD

**Issue by oBlissing** [libris/lxlviewer#8]
More like this

![screenshot 2016-06-30 13 37 20](https://cloud.githubusercontent.com/assets/3618525/16486892/d02a07a6-3ec7-11e6-8edd-d58422ca5263.png)

**Comment by oBlissing** [comment]
More like this

![screenshot 2016-06-30 13 37 20](https://cloud.githubusercontent.com/assets/3618525/16486892/d02a07a6-3ec7-11e6-8edd-d58422ca5263.png)

**Comment by niklasl** [comment]
👍
